### ISSUE TITLE
MoG changes

### ISSUE THREAD

**Issue by timrossback** [qld-gov-au/qg-web-template#443]
Hey,

Just wondering if this project now falls under the CHDE portfolio after the 2021 MoG changes that affected HPW, or if this project has been moved under DPC or EPW etc?

https://github.com/qld-gov-au/qg-web-template/blob/939e97e972c1e59b2133bf2dd7accd267c5177a8/product%20definitions/product%20details.md?plain=1#L3

https://github.com/qld-gov-au/qg-web-template/blob/939e97e972c1e59b2133bf2dd7accd267c5177a8/product%20definitions/product%20details.md?plain=1#L14

https://github.com/qld-gov-au/qg-web-template/blob/ac35bb3d2f69f2ee297c8a96f8e465290d6c6f42/src/docs/index.html#L82

**Comment by duttonw** [comment]
Thanks for raising this @timrossback , we will look into this internally to get it updated. This is the binary repo of https://github.com/qld-gov-au/web-template-release
